
namespace rambap.cplx.Core;

/// <summary>
/// Property of an <see cref="Pinstance"/> generated by a single <see cref="IConcept"/>
/// </summary>
public interface IInstanceConceptProperty { }

/// <summary>
/// Define the logic contructing a <see cref="Pinstance.Properties"/>
/// </summary>
public interface IConcept
{
    /// <summary>
    /// Define the logic to construct an <see cref="IInstanceConceptProperty"/> <br/>
    /// <br/>
    /// To împlement Concept behavior : <br/>
    /// 1 - Use <see cref="Support.ScanObjectContentFor"/> to analyse the template <br/>
    /// 2 - Access subcomponents to consolidate properties of subcomponents and calculate relations. <br/>
    /// 3 - Add the Concept property to the Pinstance
    /// </summary>
    /// <param name="component">A component ongoing initialisation. SubComponent are initialised</param>
    /// <returns>A newly created property to be added to this component instance, or null if none is to be added</returns>
    internal IInstanceConceptProperty? MakeBase(Component component);
}

/// <summary>
/// Typed implementation of an <see cref="IConcept"/>
/// </summary>
/// <typeparam name="T">Type of <see cref="IInstanceConceptProperty"/> produced by this concept.</typeparam>
public abstract class IConcept<T> : IConcept
    where T : IInstanceConceptProperty
{
    /// <summary>Wrap a typed implementation of <see cref="IConcept.MakeBase(Pinstance)"/></summary>
    public IInstanceConceptProperty? MakeBase(Component component) => Make(component);

    /// <summary>Typed implementation of <see cref="IConcept.MakeBase(Pinstance)"/><br/>
    /// <inheritdoc cref="IConcept.MakeBase(Pinstance, IEnumerable{Component}, Part)"/>
    /// </summary>
    public abstract T? Make(Component component);

    /// <summary>
    /// Expose GetPartConceptInitialisationData as a non-internal method, for concepts defined outside of this assembly
    /// </summary>
    protected static PCD GetPartConceptInitialisationData<PCD>(Part part)
        where PCD : new()
        => part.GetContceptInitialisationData<PCD>();
}